apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-ms-user
  labels:
    app: fiap-ms-user
spec:
  selector:
    matchLabels:
        app: fiap-ms-user
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fiap-ms-user
    spec:
      containers:
        - name: fiap-ms-user
          image: jvitoralmeida/fiap.ms-user:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
